<a href="https://colab.research.google.com/github/sr-lake/AD.Python/blob/main/Entrega_04_Numpy_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercícios


1. Importe NumPy como `np`

In [1]:
import numpy as np

2. Crie um array com 10 zeros 

In [2]:
np.zeros((10))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Crie um array com 10 'uns'

In [3]:
np.ones((10))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

4. Crie um array com 10 'cincos'

In [7]:
np.ones((10)) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

5. Crie um vetor de números inteiros de 10 ate 50

In [21]:
np.linspace(start=10, stop=50)

array([10.        , 10.81632653, 11.63265306, 12.44897959, 13.26530612,
       14.08163265, 14.89795918, 15.71428571, 16.53061224, 17.34693878,
       18.16326531, 18.97959184, 19.79591837, 20.6122449 , 21.42857143,
       22.24489796, 23.06122449, 23.87755102, 24.69387755, 25.51020408,
       26.32653061, 27.14285714, 27.95918367, 28.7755102 , 29.59183673,
       30.40816327, 31.2244898 , 32.04081633, 32.85714286, 33.67346939,
       34.48979592, 35.30612245, 36.12244898, 36.93877551, 37.75510204,
       38.57142857, 39.3877551 , 40.20408163, 41.02040816, 41.83673469,
       42.65306122, 43.46938776, 44.28571429, 45.10204082, 45.91836735,
       46.73469388, 47.55102041, 48.36734694, 49.18367347, 50.        ])

6. Crie um vetor com o numeros pares de 10 até 50

7. Crie uma matriz $3 \times 3$ com os valores de 0 até 8

8. Crie uma matriz identidade $7 \times 7$

9. Use numpy para gerar um número aleatório entre 0 e 1

10. Use o numpy para gerar 25 números aleatório de distribuição normal padrão (gaussiana com média $\mu = 0$ e desvio padrão $\sigma = 1$)

In [27]:
np.random.randint(25)

8

11. Crie a matrix abaixo

```python
array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])
```

In [ ]:
import numpy as np
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

12. Crie um array de 20 elementos igulmente espaçados entre 0 e 1:

13. Dada a matrix abaixo,

```python
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
```

obtenha as seguintes matrizes por indexação e se necessário, reshape:
* 
```python
array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])
```
* 
```python
array([[ 2],
       [ 7],
       [12]])
```
* 
```python
array([21, 22, 23, 24, 25])
```
* 
```python
array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
```

14. Some todos os valores da matriz

15. Some todas as colunas da matriz

16. Calcule o desvio padrão por coluna