<a href="https://colab.research.google.com/github/sr-lake/AD.Python/blob/main/FIT_Entrega_01_Numpy_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercícios


1. Importe NumPy como `np`

In [43]:
import numpy as np
import pandas as pd

2. Crie um array com 10 zeros 

In [5]:
np.zeros((10))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Crie um array com 10 'uns'

In [6]:
np.ones((10))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

4. Crie um array com 10 'cincos'

In [7]:
np.ones((10)) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

5. Crie um vetor de números inteiros de 10 ate 50

In [8]:
np.arange(start=10, stop=51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

6. Crie um vetor com o numeros pares de 10 até 50

In [9]:
np.arange(10, 50, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

7. Crie uma matriz $3 \times 3$ com os valores de 0 até 8

In [10]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

8. Crie uma matriz identidade $7 \times 7$

In [11]:
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

9. Use numpy para gerar um número aleatório entre 0 e 1

In [12]:
np.random.rand(1)

array([0.78696796])

10. Use o numpy para gerar 25 números aleatório de distribuição normal padrão (gaussiana com média $\mu = 0$ e desvio padrão $\sigma = 1$)

In [13]:
np.random.rand(5,5)

array([[0.20472301, 0.98832053, 0.61428387, 0.88584698, 0.02135493],
       [0.11227058, 0.53029039, 0.31077202, 0.19280303, 0.60164009],
       [0.78039592, 0.65647282, 0.46906242, 0.16135295, 0.86782462],
       [0.43585274, 0.42208555, 0.64082264, 0.55915646, 0.65208592],
       [0.65944161, 0.90833533, 0.58766685, 0.93475932, 0.88623682]])

11. Crie a matrix abaixo

```python
array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])
```

In [14]:
import numpy as np
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

12. Crie um array de 20 elementos igulmente espaçados entre 0 e 1:

In [15]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

13. Dada a matrix abaixo,

```python
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
```

obtenha as seguintes matrizes por indexação e se necessário, reshape:
* 
```python
array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])
```
* 
```python
array([[ 2],
       [ 7],
       [12]])
```
* 
```python
array([21, 22, 23, 24, 25])
```
* 
```python
array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
```

In [16]:
A = np.arange(1,26).reshape(5,5)
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [17]:
A[2:6,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

14. Some todos os valores da matriz

In [42]:
np.sum(A)

325

In [27]:
np.sum(A[:])

325

15. Some todas as colunas da matriz

In [54]:
A.sum(axis=0)

array([55, 60, 65, 70, 75])

16. Calcule o desvio padrão por coluna

In [48]:
A.std()

7.211102550927978